spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://120.78.142.13:12345/miaosha?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    url: jdbc:mysql://127.0.0.1:12345/miaosha?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: qwedsazxc123
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-test-query: SELECT 1
  redis:
    host: 127.0.0.1
    port: 8083
    username: MuggleLee
    password: qwedsazxc123
    timeout: 10s
    jedis:
      pool:
        min-idle: 100
        max-active: 500
#    lettuce:
#      pool:
#        min-idle: 0
#        max-idle: 8
#        max-active: 8
#        max-wait: -1ms
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  tomcat:
    accesslog:
      enabled: true
      directory: E:/tomcat
      pattern: '%h %l %u %t "%r%" %s %b %D'
    #默认是100
    accept-count: 500
    #默认是10000
    max-connections: 15000
    #默认是200
    max-threads: 1000
    #默认是10
    min-spare-threads: 200
